import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { cookies } from "next/headers";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner"
import { AuthProvider } from "@/context/UserContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // Define a CSS variable
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies(); // Get all cookies
  const theme = cookieStore.get("theme")?.value || "light";

  return (
    <html lang="en" className={montserrat.variable + " " + cn(theme === "dark" && "dark") }>
      <AuthProvider>
      <body className="bf-slate-50 ">
        <Navbar/>
        {children}
        <Toaster position="top-right" richColors />
      </body>
      </AuthProvider>
    </html>
  );
}
